export const FETCH_CITIES_REQUEST = "FETCH_CITIES_REQUEST";
export const FETCH_CITIES_SUCCESS = "FETCH_CITIES_SUCCESS";
export const FETCH_CITIES_FAILURE = "FETCH_CITIES_FAILURE";

export const SEARCH_CITY = "SEARCH_CITY";

export const FETCH_ITINERARIES_REQUEST = "FETCH_ITINERARIES_REQUEST";
export const FETCH_ITINERARIES_SUCCESS = "FETCH_ITINERARIES_SUCCESS";
export const FETCH_ITINERARIES_FAILURE = "FETCH_ITINERARIES_FAILURE";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const REQUEST_GET_COMMENTS = "REQUEST_GET_COMMENTS";
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export const ERROR_GET_COMMENTS = "ERROR_GET_COMMENTS";

export const REQUEST_POST_COMMENT = "REQUEST_POST_COMMENT";
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS";
export const ERROR_POST_COMMENT = "ERROR_POST_COMMENT";

export const REQUEST_DELETE_COMMENT = "REQUEST_DELETE_COMMENT";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const ERROR_DELETE_COMMENT = "ERROR_DELETE_COMMENT";
